# Generated by Django 5.0.14 on 2026-04-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_name_user_first_name_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document_type',
            field=models.CharField(choices=[('CPF', 'Cpf'), ('CNPJ', 'Cnpj')], max_length=15),
        ),
    ]
