# Generated by Django 5.0.14 on 2026-04-20 22:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_address_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('transfer_type', models.CharField(choices=[('PIX', 'Pix'), ('TED', 'Transferência Eletrônica Disponível'), ('DOC', 'Documento de Ordem de Crédito')], max_length=12)),
                ('transfer_status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou')], default='PENDING', max_length=12)),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('transfer_created', models.DateTimeField(auto_now=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_send', to='accounts.client')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_received', to='accounts.client')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='transactions_transaction_transaction_amount_must_be_positive'),
        ),
    ]
