# Generated by Django 5.0.14 on 2026-04-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
