# Generated by Django 5.0.14 on 2026-05-02 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_blocked_balance_user_is_staff_and_more'),
        ('transactions', '0003_transaction_external_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_send', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_type',
            field=models.CharField(choices=[('PIX', 'Pix'), ('TED', 'Transferência Eletrônica Disponível'), ('DOC', 'Documento de Ordem de Crédito'), ('DEPOSIT', 'Depósito')], max_length=12),
        ),
    ]
